const projects = [
  {
    id: 1,
    title: 'project.contador_regressivo.title',
    description: 'project.contador_regressivo.description',
    imagem: 'https://i.imgur.com/vK1fQVK.png',
    link: 'https://github.com/HugoZAuad/Desafio-Contdown',
    siteLink: 'https://desafio-contdown.vercel.app',
  },
  {
    id: 2,
    title: 'project.controle_de_produtos.title',
    description: 'project.controle_de_produtos.description',
    imagem: 'https://i.imgur.com/TPQKfYD.png',
    link: 'https://github.com/HugoZAuad/Controle_produtos',
    siteLink: 'https://controle-produtos-phi.vercel.app',
  },
  {
    id: 3,
    title: 'project.lista_de_tarefas.title',
    description: 'project.lista_de_tarefas.description',
    imagem: 'https://i.imgur.com/JqdUU8q.png',
    link: 'https://github.com/HugoZAuad/ToDo-Lista',
    siteLink: 'https://to-do-listas.vercel.app',
  },
  {
    id: 4,
    title: 'project.pesquisador_de_paises.title',
    description: 'project.pesquisador_de_paises.description',
    imagem: 'https://i.imgur.com/OOuLTW8.png',
    link: 'https://github.com/HugoZAuad/Pesquisador_Paises',
    siteLink: 'https://pesquisador-paises.vercel.app',
  },
  {
    id: 5,
    title: 'project.landpage_dnc.title',
    description: 'project.landpage_dnc.description',
    imagem: 'https://i.imgur.com/TWoOFwj.png',
    link: 'https://github.com/HugoZAuad/Landpage_DNC',
    siteLink: 'https://landpage-dnc.vercel.app',
  },
  {
    id: 6,
    title: 'project.climotex.title',
    description: 'project.climotex.description',
    imagem: 'https://i.imgur.com/3WB2yLI.png',
    link: 'https://github.com/HugoZAuad/ClimoTex',
    siteLink: 'https://climotex.vercel.app',
  },
  {
    id: 7,
    title: 'project.js_game.title',
    description: 'project.js_game.description',
    imagem: 'https://i.imgur.com/FsVmIKu.png',
    link: 'https://github.com/HugoZAuad/JSGAME',
    siteLink: 'https://jsgame-seven.vercel.app',
  },
  {
    id: 8,
    title: 'project.faq_frontend_mentor.title',
    description: 'project.faq_frontend_mentor.description',
    imagem: 'https://i.imgur.com/2cJAhzU.png',
    link: 'https://github.com/HugoZAuad/Projeto_FAQ',
    siteLink: 'https://projeto-faq-iota.vercel.app',
  },
  {
    id: 9,
    title: 'project.clone_yu_gi_oh.title',
    description: 'project.clone_yu_gi_oh.description',
    imagem: 'https://i.imgur.com/bBHZXum.png',
    link: 'https://github.com/HugoZAuad/clone-yugioh-devemdobro-',
    siteLink: 'https://clone-yugioh-devemdobro.vercel.app',
  },
  {
    id: 10,
    title: 'project.spotify_imersao.title',
    description: 'project.spotify_imersao.description',
    imagem: 'https://i.imgur.com/17w3Po7.png',
    link: 'https://github.com/HugoZAuad/Imersao_FrontEND_Alura',
    siteLink: 'https://spotify-imersao.netlify.app',
  },
  {
    id: 11,
    title: 'project.autenticacao_google.title',
    description: 'project.autenticacao_google.description',
    imagem: 'https://i.imgur.com/Pu4wmRf.png',
    link: 'https://github.com/HugoZAuad/Autentica-o_google-firebase',
    siteLink: 'https://autentica-o-google-firebase.vercel.app',
  },
]

export default projects
