const projects = [
  {
    id: 1,
    title: 'project.salesdashboard.title',
    description: 'project.salesdashboard.description',
    imagem: 'https://i.imgur.com/taqeZ4y.png',
    link: 'https://github.com/HugoZAuad/Sales-Dashboard',
    siteLink: 'https://sales-dashboard-hza.vercel.app/',
  },
  {
    id: 2,
    title: 'project.controle_de_produtos.title',
    description: 'project.controle_de_produtos.description',
    imagem: 'https://i.imgur.com/TPQKfYD.png',
    link: 'https://github.com/HugoZAuad/Controle_produtos',
    siteLink: 'https://controle-produtos-phi.vercel.app',
  },
  {
    id: 3,
    title: 'project.desafio1.title',
    description: 'project.desafio1.description',
    imagem: 'https://i.imgur.com/M2urbZ7.png',
    link: 'https://github.com/HugoZAuad/Desafio-LP-ARQ_RID66155?tab=readme-ov-file',
    siteLink: 'https://land-arq.netlify.app/',
  },
  {
    id: 4,
    title: 'project.pesquisador_de_paises.title',
    description: 'project.pesquisador_de_paises.description',
    imagem: 'https://i.imgur.com/OOuLTW8.png',
    link: 'https://github.com/HugoZAuad/Pesquisador_Paises',
    siteLink: 'https://pesquisador-paises.vercel.app',
  },
  {
    id: 5,
    title: 'project.projectarq_dnc.title',
    description: 'project.projectarq_dnc.description',
    imagem: 'https://i.imgur.com/iTY0qYw.png',
    link: 'https://github.com/HugoZAuad/PROJETO_ARQUITETURA',
    siteLink: 'https://projeto-arquitetura-indol.vercel.app/',
  },
  {
    id: 6,
    title: 'project.desafio4.title',
    description: 'project.desafio4.description',
    imagem: 'https://i.imgur.com/WcBSmvE.png',
    link: 'https://github.com/HugoZAuad/DESAFIO-4---PORTFOLIO_REACT__RID66155',
    siteLink: 'https://portfolioreacthugozauad.vercel.app/',
  },
  {
    id: 7,
    title: 'project.js_game.title',
    description: 'project.js_game.description',
    imagem: 'https://i.imgur.com/FsVmIKu.png',
    link: 'https://github.com/HugoZAuad/JSGAME',
    siteLink: 'https://jsgame-seven.vercel.app',
  },
  {
    id: 8,
    title: 'project.faq_frontend_mentor.title',
    description: 'project.faq_frontend_mentor.description',
    imagem: 'https://i.imgur.com/2cJAhzU.png',
    link: 'https://github.com/HugoZAuad/Projeto_FAQ',
    siteLink: 'https://projeto-faq-iota.vercel.app',
  },
  {
    id: 9,
    title: 'project.desafio3.title',
    description: 'project.desafio3.description',
    imagem: 'https://i.imgur.com/iuZUcp1.png',
    link: 'https://github.com/HugoZAuad/DESAFIO-3---BOARD-TASK__RID66155',
    siteLink: 'https://desafio-3-board-task-rid-66155.vercel.app/',
  },
  {
    id: 10,
    title: 'project.autenticacao_google.title',
    description: 'project.autenticacao_google.description',
    imagem: 'https://i.imgur.com/Pu4wmRf.png',
    link: 'https://github.com/HugoZAuad/Autentica-o_google-firebase',
    siteLink: 'https://autentica-o-google-firebase.vercel.app',
  },
]

export default projects
